### ISSUE TITLE
Incompatible with Notepad++ 7.5.8 x64

### ISSUE THREAD

**Issue by boubou** [viper3400/NppRegExTractor#5]
Incompatible with Notepad++ 7.5.8 x64.
I tried to install it with Plugin Manager and when Notepad++ restart, I got an error of loading the plugin.

**Comment by viper3400** [comment]
Hi @sboulianne 

Is this the error you've got:
![grafik](https://user-images.githubusercontent.com/11006334/43357806-488b9380-9287-11e8-8d79-4f7709a75287.png)

Not sure what's the reason to this. I don't know if I'm able to fix this soon. There has been some discussion about future of the Notepad++ in the past, but I lost track due to other things.

As the plugin is just a wrapper around the RegExtractor standalone app you may use the standalone application meanwhile: https://github.com/viper3400/RegExTractor/releases

**Comment by chcg** [comment]
With N++7.6 32bit I don't see the reported problem, but

---------------------------
Plugin Crash
---------------------------
NppRegExTractorPlugin.dll just crashed in
runPluginCommand(size_t i : 36)
---------------------------
OK   
---------------------------

on clicking "Open NppRegExTractor" from plugin menu. About box is ok.

**Comment by viper3400** [comment]
Hi @chcg 

Seems you've found a solution for an integrated plugin manager. 🥇 

I suppose the reported problem in this issue is indeed just a problem with the x64 version.

I've installed N++ 7.6 x32 but can't reproduce this error. The plugin dialog opens as supposed. It's a .NET implementation and still based on .NET Framework 3.5, maybe this could be a problem, too.

It's a fact that I'm currently not using the tool for myself, either the plugin nor the native app (https://github.com/viper3400/RegExTractor). There is also no progress in this issue since it was reported.

So if the plugin is really that instable we should cosinder to mark it as instable or remove it from plugin manager list? 

![npp7-6](https://user-images.githubusercontent.com/11006334/48862286-2f705a80-edc6-11e8-9bd7-e5f190b5e332.png)

**Comment by chcg** [comment]
The issue I mentioned occures for both 32bit and 64bit, if the zip is placed as is under ../plugins/NppRegExTractorPlugin
with
NppRegExTractorPlugin.dll
and 
subdir RegExTractor.
It doesn't happen if the RegExTractor is placed directly at plugins dir level.

**Comment by chcg** [comment]
Starting with N++ 7.5.8 as preparation for the new pluginAdmin system not just .../plugins directory is searched for plugins, but also all subdirs with dlls named after the subdir. So  RegExTractor.dll is tested if is a valid N++ plugin dll and therefore the warning about the incompatible plugin appears.

As written above the easy workaround to shift it one level down seems to be not possible as this dir seems to be not on the search path.

**Comment by chcg** [comment]
See https://github.com/morbac/xmltools/issues/12#issuecomment-440786042 for the requests to get the current install locations. Probably not supported yet by https://github.com/kbilsted/NotepadPlusPlusPluginPack.Net.

**Comment by viper3400** [comment]
@chcg okay, I will have a look at it. Thanks so far for the details.

**Comment by viper3400** [comment]
I was able to reproduce the issue. 

While it was a quick win to include the x64 version into build a year ago it'll take some more effort to solve this one. At least the latest version of https://github.com/kbilsted/NotepadPlusPlusPluginPack.Net should be implemented. The current version I use is about three years old.

Will take some time.

**Comment by poebrand** [comment]
@viper3400 ,

Can you please provide an update on this issue?

**Comment by viper3400** [comment]
Hi @poebrand ,

Do you use the NPP plugin? If so, could you try the native app?
https://github.com/viper3400/RegExTractor/releases/tag/1.3.4
The the plugin is just a wrapper for https://github.com/viper3400/RegExTractor.

**Comment by poebrand** [comment]
Thanks, the native app does run.

**Comment by viper3400** [comment]
Solved with version 2.1, version is available via plugin manager in NPP.

**Comment by poebrand** [comment]
Awesome, thanks!
